version: '3.4'

services:
  mldockercomposeapp:
    image: mldockercomposeapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=mlusername
      - DB_PASSWORD=mlpassword
      - DB_NAME=mldb
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mldb
      MYSQL_USER: mlusername
      MYSQL_PASSWORD: mlpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

